### 1. REGISTRO DE USUARIO (POST /api/auth/register)
# Prueba la creación de usuario. Guarda el token en la variable {{authToken}}

POST http://localhost:4000/api/auth/register
Content-Type: application/json

{
    "name": "Admin Test",
    "email": "admin@test.com",
    "password": "securepassword",
    "country": "Peru",
    "role": "user" 
}

### 2. CREAR CATEGORÍA (POST /api/categories)


POST http://localhost:4000/api/categories
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5MjkxZjUwNWJhZDc4NDQzYzgyMjZmZSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc2NDMwMjY3MiwiZXhwIjoxNzY2ODk0NjcyfQ.609tRsYR4AJzY7KduaSqp6WzZgPfNFAWrKSBj9NBq_s

{
    "name": "Videojuegos",
    "description": "Juegos digitales y físicos para consolas."
}




### 1. REGISTRO DE Administrador
POST http://localhost:4000/api/auth/register
Content-Type: application/json

{
    "name": "Super Admin",
    "email": "superadmin@test.com", 
    "password": "securepassword",
    "country": "Peru",
    "role": "admin" 
}


### LISTAR TODAS LAS CATEGORÍAS (Para copiar los IDs)
GET http://localhost:4000/api/categories